#!/usr/bin/env bash
# ─── Social Forge Installer ────────────────────────────────────────────
# Usage: curl -fsSL https://raw.githubusercontent.com/ishan-parihar/social-forge/main/scripts/install.sh | bash
#
# Detects your OS/arch, downloads the latest musl binary from GitHub
# Releases, sets up the directory structure, creates a .env from the
# template, and optionally installs the systemd service + AI Agent skill.
# ────────────────────────────────────────────────────────────────────────
set -euo pipefail

REPO="ishan-parihar/social-forge"
APP_NAME="social-forge"

# ── Colors ────────────────────────────────────────────────────────────
RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'
CYAN='\033[0;36m'; NC='\033[0m'
log()  { echo -e "  ${GREEN}✓${NC} $1"; }
warn() { echo -e "  ${YELLOW}⚠${NC} $1"; }
err()  { echo -e "  ${RED}✗${NC} $1"; exit 1; }
info() { echo -e "  ${CYAN}→${NC} $1"; }

# ── Help flag ─────────────────────────────────────────────────────────
if [ "${1:-}" = "--help" ] || [ "${1:-}" = "-h" ]; then
  echo "Social Forge Installer"
  echo ""
  echo "Usage: curl -fsSL https://raw.githubusercontent.com/$REPO/main/scripts/install.sh | bash"
  echo ""
  echo "Environment variables:"
  echo "  INSTALL_DIR    Installation directory (default: $HOME/social-forge)"
  echo "  BIN_DIR        Binary directory (default: /usr/local/bin)"
  echo "  SKIP_SERVICE   Skip systemd service setup (default: false)"
  echo "  SKIP_SKILL     Skip AI Agent skill installation (default: false)"
  echo "  VERSION        Specific version tag to install (default: latest)"
  echo ""
  exit 0
fi

# ── Platform detection ────────────────────────────────────────────────
ARCH=$(uname -m)
OS=$(uname -s | tr '[:upper:]' '[:lower:]')

case "$ARCH" in
  x86_64|amd64)  ARCH="x64"   ;;
  aarch64|arm64) ARCH="arm64"  ;;
  *) err "Unsupported architecture: $ARCH. Expected x86_64 or aarch64." ;;
esac

case "$OS" in
  linux)  ARTIFACT="social-forge-linux-${ARCH}"  ;;
  darwin) ARTIFACT="social-forge-macos-${ARCH}"  ;;
  *) err "Unsupported OS: $OS. Expected linux or darwin." ;;
esac

# ── Configurable paths ────────────────────────────────────────────────
INSTALL_DIR="${INSTALL_DIR:-$HOME/social-forge}"
BIN_DIR="${BIN_DIR:-/usr/local/bin}"
SKIP_SERVICE="${SKIP_SERVICE:-false}"
SKIP_SKILL="${SKIP_SKILL:-false}"
VERSION="${VERSION:-latest}"

# ── Pre-flight checks ────────────────────────────────────────────────
info "Platform: $OS/$ARCH"
info "Target:   $INSTALL_DIR"

# Check for curl
if ! command -v curl &>/dev/null; then
  err "curl is required. Install it first: apt install curl / brew install curl"
fi

# Check for sudo when needed
SUDO=""
for dir in "$BIN_DIR" /etc/systemd/system; do
  if [ ! -w "$dir" ] && [ -d "$dir" ] 2>/dev/null || [ "$dir" = "$BIN_DIR" ]; then
    if command -v sudo &>/dev/null; then
      SUDO="sudo"
    fi
    break
  fi
done

# ── Resolve latest version ────────────────────────────────────────────
if [ "$VERSION" = "latest" ]; then
  info "Resolving latest release..."
  VERSION=$(curl -fsSL "https://api.github.com/repos/$REPO/releases/latest" \
    | grep '"tag_name":' | sed 's/.*"tag_name": "\(.*\)",/\1/')
  if [ -z "$VERSION" ]; then
    err "Failed to resolve latest release tag. Check your network or set VERSION=v0.x.y"
  fi
  log "Latest release: $VERSION"
else
  info "Installing version: $VERSION"
fi

DOWNLOAD_URL="https://github.com/$REPO/releases/download/$VERSION/$ARTIFACT"

# ── Create directories ────────────────────────────────────────────────
mkdir -p "$INSTALL_DIR"/{data/media,data/telegram,data/whatsapp,migrations}
log "Created directory structure at $INSTALL_DIR"

# ── Download binary ───────────────────────────────────────────────────
info "Downloading $ARTIFACT..."
TMP_BIN=$(mktemp)
trap 'rm -f "$TMP_BIN"' EXIT

HTTP_CODE=$(curl -fsSL -w '%{http_code}' -o "$TMP_BIN" "$DOWNLOAD_URL" 2>/dev/null || echo "000")
if [ "$HTTP_CODE" != "200" ]; then
  err "Download failed (HTTP $HTTP_CODE). URL: $DOWNLOAD_URL"
fi
chmod +x "$TMP_BIN"
log "Downloaded $ARTIFACT ($(du -h "$TMP_BIN" | cut -f1))"

# ── Install binary ─────────────────────────────────────────────────────
if [ -w "$BIN_DIR" ]; then
  mv "$TMP_BIN" "$BIN_DIR/$APP_NAME"
else
  $SUDO mv "$TMP_BIN" "$BIN_DIR/$APP_NAME"
fi
log "Installed binary to $BIN_DIR/$APP_NAME"

# Verify
"$BIN_DIR/$APP_NAME" --version &>/dev/null || \
  "$BIN_DIR/$APP_NAME" --help &>/dev/null || \
  warn "Binary installed but --version check produced no output (may be expected)"

# ── Create .env from template ─────────────────────────────────────────
if [ ! -f "$INSTALL_DIR/.env" ]; then
  cat > "$INSTALL_DIR/.env" <<- 'ENVEOF'
# ─── Social Forge Configuration ─────────────────────────────────
# Generated by install.sh — update with your platform credentials.
DATABASE_URL=postgres://social_forge:social_forge@localhost:5432/social_forge

# APP_URL is your public-facing URL (used for OAuth redirects).
# Meta platforms (Instagram, Threads) REQUIRE HTTPS.
APP_URL=https://localhost:6543

# JWT secret — change this to a random 64-hex string
# JWT_SECRET=

# Security: 64 hex chars — encrypts OAuth tokens at rest
# TOKEN_ENCRYPTION_KEY=

# ── PostgreSQL (Docker) ────────────────────────────────────────
# If you use the provided docker-compose.yml, these are the defaults:
# POSTGRES_USER=social_forge
# POSTGRES_PASSWORD=social_forge
# POSTGRES_DB=social_forge

# ── Platform Credentials ────────────────────────────────────────
# Uncomment and add your API keys / tokens as needed.
# See https://github.com/ishan-parihar/social-forge for full docs.
ENVEOF
  log "Created .env at $INSTALL_DIR/.env (edit with your credentials)"
else
  warn ".env already exists at $INSTALL_DIR/.env — skipping"
fi

# ── Download docker-compose.yml and migrations ────────────────────────
info "Fetching supporting files..."
BASE="https://raw.githubusercontent.com/$REPO/main"

# docker-compose
if [ ! -f "$INSTALL_DIR/docker-compose.yml" ]; then
  curl -fsSL -o "$INSTALL_DIR/docker-compose.yml" "$BASE/docker-compose.yml" 2>/dev/null && \
    log "Downloaded docker-compose.yml" || warn "Failed to download docker-compose.yml"
fi

# Migrations
MIGRATIONS=$(curl -fsSL "$BASE/migrations/" 2>/dev/null | grep -oP 'href="\K\d+[^"]*\.sql' | head -20 || echo "")
if [ -n "$MIGRATIONS" ]; then
  for m in $MIGRATIONS; do
    curl -fsSL -o "$INSTALL_DIR/migrations/$m" "$BASE/migrations/$m" 2>/dev/null || true
  done
  log "Downloaded migration files"
fi

# Startup script (Linux)
if [ "$OS" = "linux" ]; then
  curl -fsSL -o "$INSTALL_DIR/social-forge-start.sh" "$BASE/scripts/social-forge-start.sh" 2>/dev/null && \
    chmod +x "$INSTALL_DIR/social-forge-start.sh" && \
    log "Downloaded social-forge-start.sh" || warn "Failed to download startup script"
fi

# ── Install AI Agent Skill ────────────────────────────────────────────
if [ "$SKIP_SKILL" != "true" ]; then
  SKILL_DIR="$HOME/.agents/skills/social-forge-agent"
  mkdir -p "$SKILL_DIR/references"

  curl -fsSL -o "$SKILL_DIR/SKILL.md" "$BASE/skills/social-forge-agent/SKILL.md" 2>/dev/null && \
    log "Installed AI Agent skill to $SKILL_DIR" || \
    warn "Failed to download skill SKILL.md"

  for ref in references/providers.md; do
    curl -fsSL -o "$SKILL_DIR/$ref" "$BASE/skills/social-forge-agent/$ref" 2>/dev/null || true
  done
fi

# ── Install systemd service (Linux) ───────────────────────────────────
if [ "$OS" = "linux" ] && [ "$SKIP_SERVICE" != "true" ]; then
  SERVICE_FILE="/etc/systemd/system/social-forge.service"

  if [ -f "$SERVICE_FILE" ]; then
    warn "systemd service already exists at $SERVICE_FILE — skipping"
  else
    # Download and install service file + startup script
    $SUDO curl -fsSL -o "$SERVICE_FILE" "$BASE/scripts/social-forge.service" 2>/dev/null && {
      # Fix paths in startup script to point to INSTALL_DIR
      $SUDO sed -i "s|APP_DIR=\"/home/ishanp/Documents/GitHub/MY-PROJECTS/MCP-AND-CLIS/social-forge\"|APP_DIR=\"$INSTALL_DIR\"|" \
        "$INSTALL_DIR/social-forge-start.sh" 2>/dev/null || true
      $SUDO sed -i "s|User=ishanp|User=$(whoami)|" "$SERVICE_FILE" 2>/dev/null || true
      $SUDO sed -i "s|Group=ishanp|Group=$(whoami)|" "$SERVICE_FILE" 2>/dev/null || true

      # Fix ExecStart path
      $SUDO sed -i "s|ExecStart=/usr/local/bin/social-forge-start.sh|ExecStart=$INSTALL_DIR/social-forge-start.sh|" \
        "$SERVICE_FILE" 2>/dev/null || true

      $SUDO systemctl daemon-reload 2>/dev/null || true

      log "systemd service installed at $SERVICE_FILE"
      echo ""
      echo "  To enable and start:"
      echo "    sudo systemctl enable social-forge --now"
      echo ""
      echo "  To view logs:"
      echo "    sudo journalctl -u social-forge -f"
    } || warn "Failed to install systemd service"
  fi
fi

# ── Done ──────────────────────────────────────────────────────────────
echo ""
echo -e "  ${GREEN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "  ${GREEN}  Social Forge installed successfully!${NC}"
echo -e "  ${GREEN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo ""
echo "  Binary:       $BIN_DIR/$APP_NAME"
echo "  Config:       $INSTALL_DIR/.env"
echo "  Data dir:     $INSTALL_DIR/data/"
echo "  Version:      $VERSION"
echo ""
echo "  Quick start:"
echo ""
echo "  1. Edit $INSTALL_DIR/.env with your platform credentials"
echo "  2. Start PostgreSQL: cd $INSTALL_DIR && docker compose up -d postgres"
echo "  3. Run the server:  $BIN_DIR/$APP_NAME serve"
echo ""
echo "  The server auto-applies migrations on startup, generates a"
echo "  self-signed TLS cert (when APP_URL uses https://), and"
echo "  listens on the port configured in APP_URL."
echo ""
echo "  Need help?  $BIN_DIR/$APP_NAME --help"
echo "  Docs:       https://github.com/$REPO"
